on:
  push:
    branches:
      - main  # main 브랜치에 푸시 시 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub에서 사용할 실행 환경

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Docker 환경
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker 로그인 (Docker Hub, ECR 등)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 로그인 사용자명
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 로그인 비밀번호

    # 6. SSH 설정: GitHub Secrets에서 EC2 접근에 필요한 키와 주소 설정
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # GitHub Secrets에 저장된 EC2 SSH 개인 키

    # 7. SSH를 통해 EC2 인스턴스에 접속하여 Docker Compose 실행
    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@43.202.100.85 "cd /home/ubuntu && sudo docker compose up -d"
      env:
        PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}  # SSH 키

    # 8. (선택사항) EC2 상태 확인
    - name: Verify deployment
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@43.202.100.85 "docker ps"
