on:
  push:
    branches:
      - main  # main 브랜치에 푸시 시 실행

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # GitHub에서 사용할 실행 환경

    steps:
    # 1. 리포지토리 체크아웃
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Docker 환경
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 3. Docker 로그인 (Docker Hub, ECR 등)
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub 로그인 사용자명
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub 로그인 비밀번호
    # compose 파일 복사 및 수정    
    - name: Deploy to EC2 using SSH
      uses: appleboy/ssh-action@v0.1.0
      with:
        host: 43.202.100.85
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        port: 22
        script: |
          sudo cp docker-compose.yml
          sudo sed -i 's@${{ secrets.DOCKER_USERNAME }}/frontend:.*@${{ secrets.DOCKER_USERNAME }}/frontend:{{ github.run_number }}@g' docker-compose.yml
          sudo sed -i 's@${{ secrets.DOCKER_USERNAME }}/backend:.*@${{ secrets.DOCKER_USERNAME }}/backend:{{ github.run_number }}@g' docker-compose.yml
          sudo docker compose up -d
        

